name: CookieClicker
version: 5.6
main: de.zillolp.cookieclicker.CookieClicker
api-version: 1.19
load: POSTWORLD
author: ZilloLP
website: https://discord.gg/NBs27JK
commands:
  cookieclicker:
    description: Manage CookieClicker
    aliases: [cc]
softdepend:
  - "Multiverse-Core"
  - "PlaceholderAPI"