package de.zillolp.cookieclicker.enums;

public enum PluginLanguage {
    PREFIX,
    NO_PERMISSION,
    ONLY_PLAYER,
    UNKNOWN_COMMAND,
    PLAYER_NOT_FOUND,

    // Interact messages
    CLICK_MESSAGE,
    COOKIE_COLLECT_MESSAGE,
    GOLDEN_COOKIE_TITLE_HEADER,
    GOLDEN_COOKIE_TITLE_FOOTER,
    COOKIE_EXPLOSION_TITLE_HEADER,
    COOKIE_EXPLOSION_TITLE_FOOTER,
    MAX_CPS,
    AFK_MESSAGE,
    PLAYER_STATS_INFO,

    // Inventory titles
    HOME_TITLE,
    SHOP_TITLE,
    PREMIUM_SHOP_TITLE,
    DESIGN_TITLE,
    BLOCK_DESIGN_TITLE,
    HIT_PARTICLE_DESIGN_TITLE,
    MENU_DESIGN_TITLE,

    // Item names
    PER_CLICK,
    YOUR_COOKIES,
    SHOP,
    DESIGN,
    BLOCK_DESIGN,
    HIT_PARTICLE_DESIGN,
    MENU_DESIGN,
    PREMIUM_PAGE,
    NEXT,
    BACK,

    // Shop
    PRICE_BUYABLE,
    PRICE_NOT_BUYABLE,
    PRICE_INFO,
    ITEM_BOUGHT,
    ITEM_BOUGHT_SELECTED,
    ITEM_INFO,
    ITEM_BOUGHT_INFO,
    ITEM_BOUGHT_SELECTED_INFO,
    MESSAGE_NOT_BUYABLE,

    // Design
    DESIGN_GLASS_NAME,

    // Holograms
    CLICKER_HOLOGRAM,
    RESET_TIMER,
    COLLECTED_COOKIE
}
